name: Ubuntu-Server
on: 
  workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa 
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@master
